/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthRouteImport } from './routes/_auth';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up';
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in';
import { Route as ApiAuthSignUpRouteImport } from './routes/api/auth.sign-up';
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth.sign-out';
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth.sign-in';
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth.session';
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$';

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any);
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any);
const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/sign-in': typeof AuthSignInRoute;
  '/sign-up': typeof AuthSignUpRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/auth/session': typeof ApiAuthSessionRoute;
  '/api/auth/sign-in': typeof ApiAuthSignInRoute;
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute;
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/sign-in': typeof AuthSignInRoute;
  '/sign-up': typeof AuthSignUpRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/auth/session': typeof ApiAuthSessionRoute;
  '/api/auth/sign-in': typeof ApiAuthSignInRoute;
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute;
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/_auth/sign-in': typeof AuthSignInRoute;
  '/_auth/sign-up': typeof AuthSignUpRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/auth/session': typeof ApiAuthSessionRoute;
  '/api/auth/sign-in': typeof ApiAuthSignInRoute;
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute;
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute;
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute;
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute;
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth/sign-up': {
      id: '/_auth/sign-up';
      path: '/sign-up';
      fullPath: '/sign-up';
      preLoaderRoute: typeof AuthSignUpRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/sign-in': {
      id: '/_auth/sign-in';
      path: '/sign-in';
      fullPath: '/sign-in';
      preLoaderRoute: typeof AuthSignInRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up';
      path: '/api/auth/sign-up';
      fullPath: '/api/auth/sign-up';
      preLoaderRoute: typeof ApiAuthSignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out';
      path: '/api/auth/sign-out';
      fullPath: '/api/auth/sign-out';
      preLoaderRoute: typeof ApiAuthSignOutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in';
      path: '/api/auth/sign-in';
      fullPath: '/api/auth/sign-in';
      preLoaderRoute: typeof ApiAuthSignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/session': {
      id: '/api/auth/session';
      path: '/api/auth/session';
      fullPath: '/api/auth/session';
      preLoaderRoute: typeof ApiAuthSessionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/$': {
      id: '/api/auth/$';
      path: '/api/auth/$';
      fullPath: '/api/auth/$';
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute;
  AuthSignUpRoute: typeof AuthSignUpRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
