/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as ApiAuthSignUpRouteImport } from './routes/api/auth.sign-up';
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth.sign-out';
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth.sign-in';
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth.session';
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$';

const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/auth/session': typeof ApiAuthSessionRoute;
  '/api/auth/sign-in': typeof ApiAuthSignInRoute;
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute;
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute;
}
export interface FileRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/auth/session': typeof ApiAuthSessionRoute;
  '/api/auth/sign-in': typeof ApiAuthSignInRoute;
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute;
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/api/auth/session': typeof ApiAuthSessionRoute;
  '/api/auth/sign-in': typeof ApiAuthSignInRoute;
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute;
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up';
  id:
    | '__root__'
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute;
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute;
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute;
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up';
      path: '/api/auth/sign-up';
      fullPath: '/api/auth/sign-up';
      preLoaderRoute: typeof ApiAuthSignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out';
      path: '/api/auth/sign-out';
      fullPath: '/api/auth/sign-out';
      preLoaderRoute: typeof ApiAuthSignOutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in';
      path: '/api/auth/sign-in';
      fullPath: '/api/auth/sign-in';
      preLoaderRoute: typeof ApiAuthSignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/session': {
      id: '/api/auth/session';
      path: '/api/auth/session';
      fullPath: '/api/auth/session';
      preLoaderRoute: typeof ApiAuthSessionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/$': {
      id: '/api/auth/$';
      path: '/api/auth/$';
      fullPath: '/api/auth/$';
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
